### PR TITLE
Responsive Grid

### PR DESCRIPTION
**Pull request by farhadgandomabadi**

### CODE REVIEW

**Comment by farhadgandomabadi** [comment]
hi nicos, I made some changes, everything is relative now but from large to small view because shapes are drawn in a larger view and we make them smaller, it is natural that they disappear and there is really not much to do. I added the tabs as well and implementing the other views. just wanted to let you know because it will be easier if you merge my code and then create the sliding design.

**Comment by farhadgandomabadi** [comment]
if you merge this version you can add your css and then I will work on drawing the shapes on other views. I will make a new pull request.

**Comment by chiknas** [comment]
Dear Farhad,
Still I believe the shapes should not disappear. We need to fix that before mergin. Also the canvas goes beyond the bottom border of the outer box.
Besides these problems everything looks good.
Regards,
Nikos.

**Comment by farhadgandomabadi** [comment]
objects are going to disappear because they move relatively and there are 2 fixed tags in the layout which makes it look worst. nothing to do there. I will fix the overlap.

**Comment by farhadgandomabadi** [comment]
actually got your point and fixing it now

**Pull request closed without merging**
